# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emma Scales
email: eks88@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  Emma Scales is a fungal biologist/microbiologist, graphic designer, and science advocate. As a Ph.D. candidate at Cornell University, she researches the molecular underpinnings of symbioses in fungi and bacteria.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  emma2117
linkedin_username: emma-scales-5aa297217

imagesurl: "/img/"
thumbsurl: "/thumbs/"

#fonts
fonts:
  use_google_fonts: true # if true will use external google_fonts url below
  preconnect_urls:
    - https://fonts.gstatic.com
  google_fonts_url: "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&display=swap"
  use_self_hosted_fonts: false # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css if true
  heading: "Fraunces"
  base: "DM-Sans"

# Build settings
theme: minima
plugins:
  - jekyll-feed

#nav bar 
header_pages:
  - _pages/about.html
  - _pages/cv.html
  - _pages/press.html
  - _pages/Blog.html
  - _pages/portfolio.html

# Get pages to actually show up: 
include:
  - _pages
  - _images
  - _includes
  - _layouts

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
